version: 0.0

Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "hello-world"
        CurrentVersion: "1"
        TargetVersion: "2"
        Alias: "latest"
