# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - name: Checking out source code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     role-to-assume: arn:aws:iam::387815262971:role/github-actions-role
    #     aws-region: us-east-1
    # - name: Running AWS CodeBuild
    #   uses: aws-actions/aws-codebuild-run-build@v1.0.12
    #   with:
    #     project-name: test-api-build
    #     env-vars-for-codebuild: CURR_VERSION,NEXT_VERSION
    #   env:
    #     CURR_VERSION: "1"
    #     NEXT_VERSION: "2"